### ISSUE TITLE
Green backlight works incorrect after all player's connections are occupied.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#12]
When player's atom is not full with connections, green backlight works well all over  the map. But when atom is full,  the backlight updates only for the visible part of the map. So that after moving away (with no connection events) all the rubish stays grey...
![1](https://cloud.githubusercontent.com/assets/17674608/13551345/e2cc50e8-e347-11e5-9f55-23c6e71cf114.png)
![2](https://cloud.githubusercontent.com/assets/17674608/13551348/e606e656-e347-11e5-8414-d35492ac4b8e.png)
![3](https://cloud.githubusercontent.com/assets/17674608/13551350/ebfa6e34-e347-11e5-8210-3da8b5067d8b.png)

**Comment by DmitryTsyganov** [comment]
Wrong function was called for color checking.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Fixed!
