### ISSUE TITLE
Резкое появление мусора.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#13]
При движении, некоторые атомы мусора постепенно выходят из-за края экрана, также постепенно заходят за край экрана. Так и должно быть. Но некоторые атомы появляются и исчезают мгновенно и целиком, не заходя за край экрана даже частично. Это не зависит от типа атома или скорости движения. То есть, частота отрисовки тут ни при чем.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Fixed.
