### ISSUE TITLE
Неправильная отрисовка игрока при параллельном открытии нескольких вкладок игры.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#14]
Если открыть вторую вкладку - отрисовка игрока прыгает , а мусор продолжает движение. (см скриншот)

На четвертой вкладке прогрузка игры либо просто не совершается либо открывается с уже запущенной стадией бага. 
На первой вкладке все остается ок. 
![default](https://cloud.githubusercontent.com/assets/17674608/13615129/dd06e058-e584-11e5-82e3-3efec0de0cc2.png)

**Comment by DmitryTsyganov** [comment]
Что значит "запущенная стадия бага"?

**Comment by DmitryTsyganov** [comment]
Это мусор перестаёт двигаться, а не игрок. Отрисовка в системе координат игрока происходит.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Запущенная стадия бага - это была альтернатива рака.
Отрисовка сейчас куда лучше. Но тем не менее, она все же нарушается при поглощении одного игрока другим. Дерево составляется некорректно. Даже порой циклично. Более того, при превращении в другой атом, игрок видит его прежнюю отрисовку, хотя свойства меняются. Враг же видит корректно измененный. Все на видео, впрочем.
https://vk.com/video?z=video55041164_456239039%2F05235e1f035324ffb4%2Fpl_updates

**Comment by DmitryTsyganov** [comment]
открыть несколько подробно описанных
