### ISSUE TITLE
Связи не рвутся при попадании по атомам нейтроном.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#16]
Нашел самую слабую комбинацию связи ( Li )---( F ) и стрельнул по ним нейтроном утроенной массы и скорости. Связи не рвутся. 
Ни разу за все время связи не рвались при выстреле нейтроном. 
![default](https://cloud.githubusercontent.com/assets/17674608/13639081/1702cd6c-e620-11e5-9eb0-2e34f1c71e03.png)

Видео.
https://vk.com/video?z=video55041164_456239040%2Fad6c7699a4fcd532e3%2Fpl_updates

**Comment by DmitryTsyganov** [comment]
Столкновения с каждым видом частиц (мусором, игроком, нейтроном, протоном) обрабтываются отдельно. При столкновении с нейтроном отрыв не происходит.
