### ISSUE TITLE
Изменение массы нейтрона приводит к вылету игроков.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#17]
Нейтоны корректно ударяются при массе 1. При массе больше 1 - стрельба нейтронами  выкидывает игроков. При массе нейтрона много больше 1 , после выстрела левая кнопка мыши работает наоборот. То есть атом движется в противоположную сторону, что вовсе странно.
Но, может, это поможет понять где баг.
Все в видео.
https://vk.com/video?z=video55041164_456239042%2F60a6d72eec9316b7c5%2Fpl_updates

**Comment by DmitryTsyganov** [comment]
Яркий пример, почему стоит писать ТЗ и диздок.
Ты забыл, что масса нейтрона у нас вычитается из массы частицы, которая его выстреливает.
Физический движок реагирует соответствующим образом.
