### ISSUE TITLE
Остановка игры при выстреле протоном после образования связей.

### ISSUE THREAD

**Issue by nochgame** [nochgames/server#19]
При стрельбе протонами бериллием в соединении со фтором происходит остановка игры. Перезагрузка не помогает.
Здесь два видео в одном. 
При вылете от Be и после вылета от Li.
![default](https://cloud.githubusercontent.com/assets/17674608/13854422/7d3b5362-ec7c-11e5-8103-0b098f98c22a.png)
https://vk.com/video?z=video55041164_456239057%2F59f860caf09dcf7980%2Fpl_updates
https://vk.com/video?z=video55041164_456239054%2F5177aad01ff039f7b9%2Fpl_updates
https://vk.com/video?section=all&z=video55041164_456239056%2Falbum55041164%2Fpl_55041164

**Comment by DmitryTsyganov** [comment]
energy can be less than 0, therefor dismountLightestBranch() in basicParticle.changeCharge() is called on body with no bonds.

**Comment by DmitryTsyganov** [comment]
Энергия связей не пересчитывалась при смене атома, отсюда неправильная работа всех функций, связанных с энергией.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
fixed
