### ISSUE TITLE
Выбрать db

### ISSUE THREAD

**Issue by sergeysova** [nochgames/server#4]
Очень важно выбрать правильную базу.

**Comment by DmitryTsyganov** [comment]
Я работал только с MySql. Mongo скоро будем изучать в технопарке, так что тоже проблем не должно быть.

**Comment by sergeysova** [comment]
@DmitryTsyganov mysql не подходит впринципе.
Если реляционная, то лучше Postgres.
Если документная, то mongo.
Хотя по мне лучше Postgres.

**Comment by DmitryTsyganov** [comment]
PostgreSQL
