### ISSUE TITLE
ES6-7 ??

### ISSUE THREAD

**Issue by sergeysova** [nochgames/server#5]
Почему не заюзаешь EcmaScript 2016?

**Comment by sergeysova** [comment]
@DmitryTsyganov

**Comment by DmitryTsyganov** [comment]
Я занимался рефакторингом. Нужно привлекать в разработку новых людей, а предыдущая версия сервера была кашей в одном файле. У меня сейчас очень мало времени, поэтому я сделал то, без чего не получится продолжить разрботку.
